### PR TITLE
OAuth modifications

### PR DESCRIPTION
**Pull request by jacobrs**
* Fixed OAuth Authentication when consuming event information from eventUrl
* Added the `Accept: application/json` to the header since the parser was a Json Parser

### CODE REVIEW

**Comment by EmilDafinov** [comment]
@jacobrs Could you keep an eye on the Travis build and tell me if it keeps failing? Technically, it won't work if you're not a contributor on the github repo. I added you, so I hope it will pass now...

**Comment by jacobrs** [comment]
@EmilDafinov Thank you for adding me to the repository. I ran the unit tests with Travis and they failed 2 times out of 3. It seems that the `RawEventHandler - should not wait for the client processing to complete before returning` is flaky. Since I only passed the test after a manual trigger, the code coverage statistics weren't sent to codacy since it was never sent the codacy token. This triggered the following error:

`[error] (*:codacyCoverage) could not find Codacy project token`

I will take a look at the test before merging and see if I can make it a bit more reliable.

**Comment by EmilDafinov** [comment]
@jacobrs yeah, test is flaky, I kept meaning to look into that. Could you add an issue? As for the codacy project token, I suspect it is related to this: https://docs.travis-ci.com/user/environment-variables#Defining-encrypted-variables-in-.travis.yml

**Comment by jacobrs** [comment]
@EmilDafinov giving the test 2 seconds to run instead of 1 worked on the first build. I think it could be a simple fix to the flaky test. 1 second was cutting it close since the mock calls took about 15mills  each and they made around 60. I will make an issue and close it if my next pull request (on this repository instead of the fork) builds on the first iteration.

**Comment by EmilDafinov** [comment]
@jacobrs Could you try creating a PR against the repo directly?

**Comment by EmilDafinov** [comment]
Changes merged in the PR mentioned above

**Pull request closed without merging**
